chore(create-farm): unified create template and upgrade dependencies
farm-fe/farm pull request #1100
Opened 2024-03-30 11:33 UTC by RSS1102

**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**

2024-04-02 00:13 UTC, wre232114 requested changes

2024-04-02 00:13 UTC, wre232114 commented on packages/create-farm/package.json
> +    "create-farm": "^1.6.3"
why add `create-farm` itself as dependencies

2024-04-03 05:20 UTC, ErKeLost commented
remove unless template @RSS1102

2024-04-03 14:23 UTC, wre232114 approved these changes

2024-04-03 14:23 UTC, merged