feat: support obj external & dts support resolvedPaths
farm-fe/farm pull request #1282
Opened 2024-05-03 10:17 UTC by shulandmimi

**Description:**

dts
- support custom resolvedPaths
- reduce product size

core
- support record external

**BREAKING CHANGE:**

**Related issue (if exists):**

close #1270 
close #1225

2024-05-05 07:22 UTC, ErKeLost approved these changes

2024-05-08 00:39 UTC, wre232114 commented on crates/core/src/config/custom.rs
> +pub const CUSTOM_CONFIG_EXTERNAL_RECORD: &str = "RECORD_EXTERNAL";
Using `external.record` would be better to normalize the name convention and make it more readable

2024-05-08 00:47 UTC, wre232114 requested changes

2024-05-08 00:47 UTC, wre232114 commented on packages/core/src/config/normalize-config/normalize-external.ts
> +export const RECORD_EXTERNAL_CUSTOM_KEY = 'RECORD_EXTERNAL';
we should add a `constants.ts` to define all the custom keys together

2024-05-09 00:32 UTC, wre232114 approved these changes

2024-05-09 11:33 UTC, merged