feat: update sourcemap of vue
farm-fe/farm pull request #147
Opened 2023-03-28 15:48 UTC by ysy945

**Description:**
- update sourcemap of vue

**BREAKING CHANGE:**
- none

**Related issue (if exists):**
close #138

2023-03-29 02:01 UTC, wre232114 requested changes

2023-03-29 02:01 UTC, wre232114 commented on js-plugins/vue/src/farm-vue-plugin.ts
> -import { error } from './utils.js';
.js suffix is needed, cause the .ts file is built to native esm

2023-03-29 13:53 UTC, Nirvana-Jie approved these changes

2023-03-30 02:53 UTC, wre232114 approved these changes

2023-03-30 02:53 UTC, merged