feat: support scss compile
farm-fe/farm pull request #152
Opened 2023-04-01 09:42 UTC by shulandmimi

**Description:**

support scss compile

**BREAKING CHANGE:**

`None`

**Related issue (if exists):**

close #121

2023-04-01 11:51 UTC, ErKeLost commented on js-plugins/sass/README.md
Readme should be in English.

2023-04-01 11:58 UTC, ErKeLost commented on js-plugins/sass/README.md
Readme should be in English.

2023-04-01 22:44 UTC, wre232114 requested changes

2023-04-01 22:44 UTC, wre232114 commented on js-plugins/sass/package.json
> +  "main": "./dist/index.js",
define `exports`, `repository`, `bugs`, `author` field in package.json, and set `type="module"`.

2023-04-01 22:44 UTC, wre232114 commented on js-plugins/sass/tsconfig.json
> +    "moduleResolution": "node"
remove this and use compile to native ESM

2023-04-01 22:47 UTC, wre232114 commented
#121 should be implemented in Rust and using https://crates.io/crates/sass-embedded.

2023-04-02 04:44 UTC, wre232114 approved these changes

2023-04-02 04:47 UTC, merged