feat(ci): add `pkg-pr` for branch `refactor/node`
farm-fe/farm pull request #1801
Opened 2024-10-03 17:17 UTC by RSS1102

**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**

2024-10-04 10:17 UTC, fu050409 approved these changes
Require a approval for a test?

2024-10-04 10:19 UTC, fu050409 requested changes

2024-10-04 10:19 UTC, fu050409 commented on .github/workflows/pkg-pr.yml
> +
Action failed here https://github.com/farm-fe/farm/actions/runs/11178171789/job/31075215488?pr=1801, a `version` field should exsits. Perhaps try with `version: 9`?

2024-10-05 19:16 UTC, RSS1102 commented
Please run again

2024-10-06 01:40 UTC, fu050409 approved these changes

2024-10-06 12:09 UTC, RSS1102 commented
Please  approved again

2024-10-07 06:45 UTC, ErKeLost approved these changes

2024-10-09 04:56 UTC, closed without merging