fix(create-farm): fix terminal color display
farm-fe/farm pull request #1986
Opened 2024-12-06 14:56 UTC by iwen-conf

…n creating the project selection frame in the terminal.

**Description:**
修复了终端中项目选择框显示异常的问题。  
- 在某些终端中，颜色配置错误导致无法正常渲染项目选择框。  
- 修改了颜色代码的 RGB 值，更改了部分ansi值从rgb改为基础 ANSI 色彩。
- 针对常见mac自带终端测试，显示正常。
- 
<img width="795" alt="image" src="https://github.com/user-attachments/assets/e8ed3e3e-8e65-4625-b9b9-a20de3d62311">

<img width="799" alt="image" src="https://github.com/user-attachments/assets/cc9acfc7-c34c-442b-9e66-961c46ec64b2">

**BREAKING CHANGE:**

此修复不会引入任何破坏性变更。

**Related issue (if exists):**
无。

2024-12-06 15:21 UTC, shulandmimi requested changes

2024-12-06 15:21 UTC, shulandmimi commented on test-project/.eslintrc.js
1. test-project 文件夹看起来并不是需要上传的文件，应该删除它，你怎么看？

2. farm 使用 changeset 管理版本发布，并且 crates/create-farm-rs 实际上在 packages/create-farm 中被打包并发布，所以你应该更新它的版本号，具体操作你可以通过 `CONTRIBUTING.md` 来获得更详细的贡献指南

2024-12-06 15:50 UTC, iwen-conf commented on test-project/.eslintrc.js
好的，非常感谢你提供的信息🙏，我做修改后再提交。

2024-12-06 17:05 UTC, iwen-conf commented on test-project/.eslintrc.js
感谢前辈的指导

1. 我已经删除了test-projects

2. 我使用了npx changeset更新了

烦请再看看是否还存在问题

2024-12-06 19:24 UTC, fu050409 requested changes

2024-12-06 19:24 UTC, fu050409 commented on CONTRIBUTING.zh-CN.md
> +git branch --set-upstream-to=upstream/main main
这处更改看起来是没有必要的？我们似乎无需追踪远程仓库，当我们使用`git clone repo`指令的时候，Git应当自动为我们处理了远程仓库。如果这不必要，考虑回滚这个更改？

2024-12-07 01:16 UTC, iwen-conf commented on CONTRIBUTING.zh-CN.md
> +git branch --set-upstream-to=upstream/main main
感谢前辈的指正🙏，这是我复制命令的时候误操作添加的，很抱歉。我已经完成了删除

2024-12-07 03:00 UTC, fu050409 approved these changes

2024-12-07 03:48 UTC, shulandmimi requested changes

2024-12-07 03:48 UTC, shulandmimi commented on .changeset/chilly-carrots-lick.md
> +"create-farm": minor
patch 而非 minor，本次更新没有破坏性更新，升级小版本号即可

2024-12-07 04:14 UTC, iwen-conf commented on .changeset/chilly-carrots-lick.md
> +"create-farm": minor
感谢前辈的指正🙏。是我对贡献指南理解的不够透彻，我已经修改了

2024-12-07 09:58 UTC, fu050409 approved these changes

2024-12-09 01:37 UTC, ErKeLost approved these changes

2024-12-09 04:40 UTC, shulandmimi approved these changes

2024-12-09 06:10 UTC, merged