fix: change the path parsing capability for @import in the less plugin
farm-fe/farm pull request #293
Opened 2023-05-07 14:41 UTC by Nirvana-Jie

**Description:**

Before it.When we use `@import 'xxxx'` in less file. It will look at the root path.I add the the dirname of resolvedPath into the options. This will help `Less` resolve paths better
**BREAKING CHANGE:**
None

**Related issue (if exists):**
None

2023-05-07 15:42 UTC, shulandmimi requested changes
https://github.com/farm-fe/farm/blob/1d244481e953fb14a46270e8f661198e80e4869c/js-plugins/less/src/index.ts#L23

`sass` -> `less`

2023-05-07 15:42 UTC, shulandmimi commented on js-plugins/less/src/index.ts
> +          options.paths.unshift(path.dirname(param.resolvedPath));
`unshift` -> `concat`?

2023-05-07 16:07 UTC, Nirvana-Jie commented on js-plugins/less/src/index.ts
> +          options.paths.unshift(path.dirname(param.resolvedPath));
got it

2023-05-08 00:07 UTC, wre232114 approved these changes

2023-05-08 01:13 UTC, shulandmimi approved these changes

2023-05-10 23:49 UTC, merged